version: '3'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - /var/data/merlin:/var/lib/postgresql/data

  merlin-dashboard:
    image: <backend-image-name>
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  merlin-web:
    image: <frontend-image-name>
    ports:
      - "3000:3000"
    depends_on:
      - merlin-dashboard
    env_file:
      - .env
