# Generated by Django 5.0.1 on 2024-01-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("content", models.TextField()),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Goal", "Goal"),
                            ("Meeting", "Meeting"),
                            ("Personal", "Personal"),
                        ],
                        default="Goal",
                        max_length=128,
                    ),
                ),
            ],
        ),
    ]
