# Generated by Django 5.0.1 on 2024-01-24 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_note_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date Created"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date Updated"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
