# Generated by Django 5.0.1 on 2024-01-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_options_alter_chapter_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
    ]
