# Generated by Django 5.0.1 on 2024-01-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_chapter_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=256, verbose_name="نام"),
        ),
    ]
