# Generated by Django 5.0.1 on 2024-01-24 11:42

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Note = apps.get_model("api", "Note")
    for row in Note.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_note_date_created_note_date_updated_note_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
