# Generated by Django 5.0.1 on 2024-01-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.chapter",
                verbose_name="چپتر",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
                verbose_name="دپارتمان",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gmail",
            field=models.CharField(
                blank=True, default="", max_length=256, null=True, verbose_name="جیمیل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="لیدر",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=256, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=256, null=True, verbose_name="موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.team",
                verbose_name="تیم",
            ),
        ),
    ]
