# Generated by Django 5.0.1 on 2024-01-24 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_note_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
