# Generated by Django 5.0.1 on 2024-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_chapter_alter_user_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="ایمیل سازمانی"
            ),
        ),
    ]
