# Generated by Django 5.0.1 on 2024-02-03 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
