# Generated by Django 5.0.1 on 2024-01-24 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_department_chapter_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"verbose_name": "چپتر", "verbose_name_plural": "چپترها"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "دپارتمان",
                "verbose_name_plural": "دپارتمان\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "verbose_name": "یادداشت",
                "verbose_name_plural": "یادداشت\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "تیم", "verbose_name_plural": "تیم\u200cها"},
        ),
        migrations.AlterField(
            model_name="chapter",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
                verbose_name="دپارتمان",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="لیدر",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(max_length=256, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="department",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=256, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(verbose_name="محتوا"),
        ),
        migrations.AlterField(
            model_name="note",
            name="date",
            field=models.DateField(verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=512, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[("Goal", "هدف"), ("Meeting", "جلسه"), ("Personal", "شخصی")],
                default="Goal",
                max_length=128,
                verbose_name="نوع",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
                verbose_name="دپارتمان",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="لیدر",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=256, verbose_name="نام"),
        ),
    ]
