# Generated by Django 5.0.1 on 2024-02-04 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_note_mentioned_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربران منشن شده",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("Goal", "هدف"),
                    ("Meeting", "جلسه"),
                    ("Personal", "شخصی"),
                    ("Task", "فعالیت"),
                ],
                default="Goal",
                max_length=128,
                verbose_name="نوع",
            ),
        ),
    ]
