# Generated by Django 5.0.1 on 2024-02-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_feedback"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("owner", "note")},
        ),
    ]
