# Generated by Django 5.0.1 on 2024-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_note_type_committee_note_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("Goal", "هدف"),
                    ("Meeting", "جلسه"),
                    ("Personal", "شخصی"),
                    ("Task", "فعالیت"),
                    ("Proposal", "پروپوزال"),
                ],
                default="Goal",
                max_length=128,
                verbose_name="نوع",
            ),
        ),
    ]
