# Generated by Django 5.0.1 on 2024-02-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_note_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("Goal", "هدف"),
                    ("Meeting", "جلسه"),
                    ("Personal", "شخصی"),
                    ("Task", "فعالیت"),
                    ("Proposal", "پروپوزال"),
                    ("message", "پیام"),
                ],
                default="Goal",
                max_length=128,
                verbose_name="نوع",
            ),
        ),
    ]
