# Generated by Django 5.0.1 on 2024-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_note_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="summary",
            field=models.TextField(blank=True, verbose_name="جمع\u200cبندی"),
        ),
    ]
