# Generated by Django 5.0.1 on 2024-03-04 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_note_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="read_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
