# Generated by Django 5.0.1 on 2024-03-10 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_note_read_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteUserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("can_view", models.BooleanField(default=False, verbose_name="مشاهده")),
                ("can_edit", models.BooleanField(default=False, verbose_name="ویرایش")),
                (
                    "can_write_summary",
                    models.BooleanField(
                        default=False, verbose_name="نوشتن جمع\u200cبندی"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.note",
                        verbose_name="یادداشت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی",
                "verbose_name_plural": "دسترسی\u200cها",
                "unique_together": {("user", "note")},
            },
        ),
    ]
