# Generated by Django 5.0.1 on 2024-03-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_noteuseraccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuseraccess",
            name="can_write_feedback",
            field=models.BooleanField(default=False, verbose_name="نوشتن فیدبک"),
        ),
    ]
