# Generated by Django 5.0.1 on 2024-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_noteuseraccess_can_view_feedbacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteuseraccess",
            name="can_view_feedbacks",
            field=models.BooleanField(
                default=False, verbose_name="مشاهده فیدبک\u200cها"
            ),
        ),
    ]
