# Generated by Django 5.0.1 on 2024-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_note_committee_user_committee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="linked_notes",
            field=models.ManyToManyField(
                blank=True,
                related_name="connected_notes",
                to="api.note",
                verbose_name="پیوندها",
            ),
        ),
    ]
