# Generated by Django 5.0.1 on 2024-04-10 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_user_level_alter_user_agile_coach"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="summary",
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "performance_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        null=True,
                        verbose_name="لیبل عملکردی",
                    ),
                ),
                (
                    "ladder_change",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        null=True,
                        verbose_name="تغییر در سطح لدر",
                    ),
                ),
                ("bonus", models.IntegerField(verbose_name="پاداش عملکردی")),
                (
                    "salary_change",
                    models.FloatField(verbose_name="تغییر پله\u200cی حقوقی"),
                ),
                (
                    "committee_date",
                    models.DateField(verbose_name="تاریخ برگزاری جلسه\u200cی کمیته"),
                ),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.note",
                        verbose_name="یادداشت",
                    ),
                ),
            ],
            options={
                "verbose_name": "جمع\u200cبندی",
                "verbose_name_plural": "جمع\u200cبندی\u200cها",
            },
        ),
    ]
