# Generated by Django 5.0.1 on 2024-04-10 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_note_summary_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteuseraccess",
            name="note",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.note",
                verbose_name="یادداشت",
            ),
        ),
        migrations.AlterField(
            model_name="noteuseraccess",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
