# Generated by Django 5.0.1 on 2024-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_noteuseraccess_note_alter_noteuseraccess_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="bonus",
            field=models.IntegerField(default=0, verbose_name="پاداش عملکردی"),
        ),
        migrations.AlterField(
            model_name="summary",
            name="committee_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاریخ برگزاری جلسه\u200cی کمیته"
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="salary_change",
            field=models.FloatField(default=0, verbose_name="تغییر پله\u200cی حقوقی"),
        ),
    ]
