# Generated by Django 5.0.1 on 2024-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_summary_bonus_alter_summary_committee_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="period",
            field=models.IntegerField(default=0, verbose_name="دوره"),
        ),
        migrations.AddField(
            model_name="note",
            name="year",
            field=models.IntegerField(default=1400, verbose_name="سال"),
        ),
    ]
