# Generated by Django 5.0.1 on 2024-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_note_period_note_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuseraccess',
            name='can_view_summary',
            field=models.BooleanField(default=False, verbose_name='مشاهده جمع\u200cبندی'),
        ),
    ]
