# Generated by Django 5.0.1 on 2024-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_noteuseraccess_can_view_summary_initialize'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='submit_status',
            field=models.IntegerField(choices=[(1, 'ثبت اولیه'), (2, 'در حال بررسی'), (3, 'ثبت نهایی')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='summary',
            name='submit_status',
            field=models.IntegerField(choices=[(1, 'ثبت اولیه'), (2, 'نهایی\u200c شده')], default=1, verbose_name='وضعیت'),
        ),
    ]
