# Generated by Django 5.0.1 on 2025-01-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_form_formassignment_question_formresponse"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="formresponse",
            unique_together={("user", "form")},
        ),
    ]
