# Generated by Django 5.0.1 on 2025-01-11 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_populate_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribe_director', to=settings.AUTH_USER_MODEL, verbose_name='دیرکتور'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=256, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ceo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_ceo', to=settings.AUTH_USER_MODEL, verbose_name='سی ای او')),
                ('cto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_cto', to=settings.AUTH_USER_MODEL, verbose_name='سی تی او')),
                ('function_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_function_owner', to=settings.AUTH_USER_MODEL, verbose_name='فانکشن اونر')),
                ('vp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_vp', to=settings.AUTH_USER_MODEL, verbose_name='وی پی')),
            ],
            options={
                'verbose_name': 'ارگانیزیشن',
                'verbose_name_plural': 'ارگانیزیشن\u200cها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organization', verbose_name='ارگانیزیشن'),
        ),
    ]
