# Generated by Django 5.0.1 on 2025-01-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_formresponse_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="formresponse",
            unique_together={("user", "form", "question")},
        ),
    ]
