# Generated by Django 5.0.1 on 2025-01-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_formresponse_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formresponse",
            name="comment",
        ),
    ]
