# Generated by Django 5.0.1 on 2025-01-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_remove_formresponse_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(
                default="A", max_length=100, verbose_name="دسته\u200cبندی"
            ),
            preserve_default=False,
        ),
    ]
