# Generated by Django 5.0.1 on 2025-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="formassignment",
            name="deadline",
            field=models.DateField(default="2099-12-31", verbose_name="ددلاین"),
            preserve_default=False,
        ),
    ]
