# Generated by Django 5.0.1 on 2025-02-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_note_summary_submit_status"),
        ("api", "0042_alter_cycle_end_date_alter_cycle_start_date"),
    ]

    operations = []
