# Generated by Django 5.0.1 on 2025-03-04 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_merge_20250220_2313"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the email template",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Subject of the email", max_length=255),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Body of the email with placeholders (e.g., {{name}}, {{role}})"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Optional metadata (e.g., version, language)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "قالبِ ایمیل",
                "verbose_name_plural": "قالب\u200cهای ایمیل",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event that triggered the email", max_length=100
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Rendered subject of the email", max_length=255
                    ),
                ),
                ("body", models.TextField(help_text="Rendered body of the email")),
                (
                    "status",
                    models.CharField(
                        default="Pending",
                        help_text="Status of the email (e.g., Sent, Failed)",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if sending failed",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the email was sent",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User to whom the email was sent",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_template",
                    models.ForeignKey(
                        help_text="Email template used for sending the email",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ ایمیل\u200cهای ارسالی",
                "verbose_name_plural": "لاگ ایمیل\u200cهای ارسالی",
            },
        ),
        migrations.CreateModel(
            name="EmailTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("new_form_assigned", "New Form Assigned"),
                            ("unchecked_form_reminder", "Unchecked Form Reminder"),
                        ],
                        help_text="Event that triggers the email",
                        max_length=100,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        help_text='Optional conditions for triggering the email (e.g., {"role": "manager"})',
                        null=True,
                    ),
                ),
                ("placeholders", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The email template to use when the trigger fires",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="api.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "تریگرِ ایمیل",
                "verbose_name_plural": "ایمیل تریگرها",
            },
        ),
    ]
