# Generated by Django 5.0.1 on 2025-03-15 10:51

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_merge_20250220_2313"),
    ]

    operations = [
        migrations.AddField(
            model_name="tribe",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tribe_director",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دیرکتور",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="product_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_manager_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PM/پروداکت منجر",
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="نام")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "ceo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_ceo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سی ای او",
                    ),
                ),
                (
                    "cto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_cto",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سی تی او",
                    ),
                ),
                (
                    "function_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_function_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فانکشن اونر",
                    ),
                ),
                (
                    "vp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_vp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="وی پی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارگانیزیشن",
                "verbose_name_plural": "ارگانیزیشن\u200cها",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.organization",
                verbose_name="ارگانیزیشن",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("Leader", "لیدر"),
                            ("CTO", "سی تی او"),
                            ("Director", "دیرکتور"),
                            ("VP", "وی پی"),
                            ("CEO", "سی ای او"),
                            ("Function Owner", "فانکشن اونر"),
                            ("Product Manager", "پروداکت منجر"),
                            ("CPO", "سی پی او"),
                        ],
                        default=api.models.RoleType.default,
                        max_length=50,
                    ),
                ),
                (
                    "role_scope",
                    models.CharField(
                        choices=[
                            ("User", "کاربر"),
                            ("Team", "تیم"),
                            ("Organization", "سازمان"),
                            ("TRIBE", "قبیله"),
                            ("Chapter", "چپتر"),
                        ],
                        default=api.models.RoleScope.default,
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش\u200cها",
                "unique_together": {("role_type", "role_scope")},
            },
        ),
        migrations.AddField(
            model_name="committee",
            name="roles",
            field=models.ManyToManyField(related_name="role_committees", to="api.role"),
        ),
    ]
