# Generated by Django 5.0.1 on 2025-04-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_merge_20250220_2313"),
        ("api", "0010_alter_feedback_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
        migrations.AddField(
            model_name="summary",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
    ]
