# Generated by Django 5.0.1 on 2025-04-12 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_add_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="cpo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_cpo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سی پی او",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="role_committees", to="api.role"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="ceo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_ceo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سی ای او",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="cto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_cto",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سی تی او",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="function_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_function_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فانکشن اونر",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="vp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_vp",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وی پی",
            ),
        ),
    ]
