# Generated by Django 5.0.1 on 2025-06-07 07:21

import api.models.cycle
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_feedback_cycle_note_cycle_summary_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=api.models.cycle.Cycle.get_current_cycle,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="cycle",
            field=models.ForeignKey(
                default=api.models.cycle.Cycle.get_current_cycle,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=api.models.cycle.Cycle.get_current_cycle,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=api.models.cycle.Cycle.get_current_cycle,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.cycle",
                verbose_name="دوره",
            ),
        ),
    ]
