# Generated by Django 5.0.1 on 2025-05-17 11:08

import api.models.role
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_organization_cpo_alter_committee_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tribe",
            name="director",
        ),
        migrations.AddField(
            model_name="organization",
            name="cfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_cfo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سی\u200cاف\u200cاو",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hr_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_hr_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر اچ\u200cآر",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sales_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_sales_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر فروش",
            ),
        ),
        migrations.AddField(
            model_name="tribe",
            name="engineering_director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="engineering_director_tribes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دیرکتور فنی",
            ),
        ),
        migrations.AddField(
            model_name="tribe",
            name="product_director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_director_tribes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دیرکتور محصولی",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hrbp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hrbp_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اچ\u200cآربی\u200cپی",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("Leader", "لیدر"),
                    ("CTO", "سی تی او"),
                    ("Product Director", "دیرکتور پروداکت"),
                    ("VP", "وی پی"),
                    ("CEO", "سی ای او"),
                    ("Function Owner", "فانکشن اونر"),
                    ("Product Manager", "پروداکت منجر"),
                    ("CPO", "سی پی او"),
                    ("HR Manager", "اچ آر منجر"),
                    ("Sales Manager", "مدیر فروش"),
                    ("CFO", "سی اف او"),
                    ("HRBP", "اچ آر بی پی"),
                    ("Engineering Director", "دیرکتور مهندسی"),
                ],
                default=api.models.role.RoleType.default,
                max_length=50,
            ),
        ),
    ]
