# Generated by Django 5.0.1 on 2025-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_rename_other_notes_oneonone_extra_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oneonone",
            name="career_summary",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name="oneonone",
            name="communication_summary",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name="oneonone",
            name="performance_summary",
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name="oneonone",
            name="personal_summary",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
