# Generated by Django 5.0.1 on 2025-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_usertimeline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oneonone",
            old_name="other_notes",
            new_name="extra_notes",
        ),
        migrations.AlterField(
            model_name="oneonone",
            name="actions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="oneonone",
            name="leader_vibe",
            field=models.CharField(
                choices=[(":)", "😊"), (":|", "😐"), (":(", "☹️")], max_length=2
            ),
        ),
    ]
