# Generated by Django 5.0.1 on 2025-07-16 13:26

import api.models.role
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_alter_oneonone_career_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="cfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_cfo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سی\u200cاف\u200cاو",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hr_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_hr_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر اچ\u200cآر",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sales_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_sales_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر فروش",
            ),
        ),
        migrations.AddField(
            model_name="tribe",
            name="engineering_director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="engineering_director_tribes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دیرکتور فنی",
            ),
        ),
        migrations.AddField(
            model_name="tribe",
            name="product_director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_director_tribes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دیرکتور محصولی",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("Leader", "لیدر"),
                            ("CTO", "سی تی او"),
                            ("Product Director", "دیرکتور پروداکت"),
                            ("VP", "وی پی"),
                            ("CEO", "سی ای او"),
                            ("Function Owner", "فانکشن اونر"),
                            ("Product Manager", "پروداکت منجر"),
                            ("CPO", "سی پی او"),
                            ("HR Manager", "اچ آر منجر"),
                            ("Sales Manager", "مدیر فروش"),
                            ("CFO", "سی اف او"),
                            ("HRBP", "اچ آر بی پی"),
                            ("Engineering Director", "دیرکتور مهندسی"),
                        ],
                        default=api.models.role.RoleType.default,
                        max_length=50,
                    ),
                ),
                (
                    "role_scope",
                    models.CharField(
                        choices=[
                            ("User", "کاربر"),
                            ("Team", "تیم"),
                            ("Organization", "سازمان"),
                            ("TRIBE", "قبیله"),
                            ("Chapter", "چپتر"),
                        ],
                        default=api.models.role.RoleScope.default,
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش\u200cها",
                "unique_together": {("role_type", "role_scope")},
            },
        ),
        migrations.AddField(
            model_name="committee",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="role_committees", to="api.role"
            ),
        ),
    ]
