# Generated by Django 5.0.1 on 2025-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_rename_other_notes_oneonone_extra_notes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="Comment",
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "نظر", "verbose_name_plural": "نظرها"},
        ),
        migrations.AlterField(
            model_name="noteuseraccess",
            name="can_view_feedbacks",
            field=models.BooleanField(default=False, verbose_name="مشاهده فیدبک‌ها"),
        ),
    ]
