# Generated by Django 5.0.1 on 2025-07-24 17:23

import api.models.organization
import api.models.role
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_organization_cfo_organization_hr_manager_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "لدر",
                "verbose_name_plural": "لدرها",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="PayBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="شماره پله"),
                ),
            ],
            options={
                "verbose_name": "پله حقوقی",
                "verbose_name_plural": "پله\u200cهای حقوقی",
                "ordering": ("number",),
            },
        ),
        migrations.RenameModel(
            old_name="UserTimeline",
            new_name="OneOnOneActivityLog",
        ),
        migrations.AddField(
            model_name="committee",
            name="committee_type",
            field=models.CharField(
                choices=[
                    ("PROMOTION", "ارتقا"),
                    ("NOTICE", "نوتیس"),
                    ("MAPPING", "مپینگ اولیه"),
                    ("EVALUATION", "ارزیابی"),
                ],
                default=api.models.organization.CommitteeType.default,
                max_length=16,
                verbose_name="نوع کمیته",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("Leader", "لیدر"),
                    ("CTO", "سی تی او"),
                    ("Product Director", "دیرکتور پروداکت"),
                    ("VP", "وی پی"),
                    ("CEO", "سی ای او"),
                    ("Function Owner", "فانکشن اونر"),
                    ("Product Manager", "پروداکت منجر"),
                    ("CPO", "سی پی او"),
                    ("HR Manager", "اچ آر منجر"),
                    ("Sales Manager", "مدیر فروش"),
                    ("CFO", "سی اف او"),
                    ("HRBP", "اچ آر بی پی"),
                    ("Engineering Director", "دیرکتور مهندسی"),
                    ("Maintainer", "نگهدارنده"),
                ],
                default=api.models.role.RoleType.default,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="LadderAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="api.ladder",
                    ),
                ),
            ],
            options={
                "verbose_name": "بعد لدر",
                "verbose_name_plural": "ابعاد لدر",
                "ordering": ("ladder", "order"),
                "unique_together": {("ladder", "code")},
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("PERFORMANCE", "عملکردی"),
                            ("CONDUCT", "رفتاری"),
                            ("OTHER", "سایر"),
                        ],
                        default="PERFORMANCE",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                ("committee_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نوتیس",
                "verbose_name_plural": "نوتیس\u200cها",
                "ordering": ("-committee_date",),
            },
        ),
        migrations.CreateModel(
            name="StockGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_grants_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "گرنت سهام",
                "verbose_name_plural": "گرنت\u200cهای سهام",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SENIORITY_CHANGE", "تغییر سطح لدر"),
                            ("PAY_CHANGE", "تغییر بسته\u200c حقوقی"),
                            ("BONUS_PAYOUT", "پرداخت پاداش"),
                            ("EVALUATION", "خروجی ارزیابی کمیته"),
                            ("MAPPING", "بازنشانی روی لدر"),
                            ("TITLE_CHANGE", "تغییر عنوان شغلی"),
                            ("STOCK_GRANT", "اعطای سهام"),
                            ("NOTICE", "نوتیس"),
                        ],
                        default="EVALUATION",
                        max_length=32,
                    ),
                ),
                ("summary_text", models.CharField(max_length=256)),
                ("effective_date", models.DateField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("visibility_mask", models.PositiveIntegerField(default=1)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد پروفایل",
                "verbose_name_plural": "رویدادهای پروفایل",
                "ordering": ("-effective_date", "-date_created"),
            },
        ),
        migrations.CreateModel(
            name="SenioritySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("overall_score", models.FloatField(default=0)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("effective_date", models.DateField()),
                ("is_redacted", models.BooleanField(default=False)),
                (
                    "ladder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.ladder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seniority_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.timelineevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسنپ\u200cشات سطح فنی",
                "verbose_name_plural": "اسنپ\u200cشات\u200cهای سطح فنی",
                "ordering": ("-effective_date",),
            },
        ),
        migrations.CreateModel(
            name="CompensationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "bonus_percentage",
                    models.FloatField(
                        default=0, help_text="Bonus as percentage of annual salary"
                    ),
                ),
                ("effective_date", models.DateField()),
                ("is_redacted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comp_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_band",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.payband",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.timelineevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسنپ\u200cشات جبران خدمات",
                "verbose_name_plural": "اسنپ\u200cشات\u200cهای جبران خدمات",
                "ordering": ("-effective_date",),
            },
        ),
        migrations.CreateModel(
            name="TitleChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("old_title", models.CharField(max_length=256)),
                ("new_title", models.CharField(max_length=256)),
                ("reason", models.TextField(blank=True, null=True)),
                ("effective_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="title_changes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تغییر عنوان",
                "verbose_name_plural": "تغییرات عنوان",
                "ordering": ("-effective_date",),
            },
        ),
        migrations.CreateModel(
            name="LadderLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("EARLY", "ابتدای سطح"),
                            ("MID", "میانه سطح"),
                            ("LATE", "انتهای سطح"),
                        ],
                        default="EARLY",
                        max_length=8,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Optional weighting when averaging across aspects.",
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="api.ladderaspect",
                    ),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="api.ladder",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطح لدر",
                "verbose_name_plural": "سطوح لدر",
                "ordering": ("ladder", "aspect", "level", "stage"),
                "unique_together": {("ladder", "aspect", "level", "stage")},
            },
        ),
    ]
