# Generated by Django 5.0.1 on 2025-06-28 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_comment_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("schema", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "فرم بازخورد",
                "verbose_name_plural": "فرم\u200cهای بازخورد",
            },
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("Goal", "هدف"),
                    ("Meeting", "جلسه"),
                    ("Personal", "شخصی"),
                    ("Task", "فعالیت"),
                    ("Proposal", "پروپوزال"),
                    ("Message", "پیام"),
                    ("Template", "قالب"),
                    ("OneOnOne", "یک\u200cبه\u200cیک"),
                    ("FeedbackRequest", "درخواست بازخورد"),
                    ("Feedback", "بازخورد"),
                ],
                default="Goal",
                max_length=128,
                verbose_name="نوع",
            ),
        ),
        migrations.AlterField(
            model_name="noteuseraccess",
            name="can_view_feedbacks",
            field=models.BooleanField(default=False, verbose_name="مشاهده نظرها"),
        ),
        migrations.AlterModelTable(
            name="comment",
            table=None,
        ),
        migrations.CreateModel(
            name="FeedbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.feedbackform",
                    ),
                ),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_request",
                        to="api.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست بازخورد",
                "verbose_name_plural": "درخواست\u200cهای بازخورد",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("content", models.TextField()),
                ("evidence", models.TextField(blank=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.cycle"
                    ),
                ),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="api.note",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.feedbackform",
                    ),
                ),
                (
                    "feedback_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_answers",
                        to="api.feedbackrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازخورد",
                "verbose_name_plural": "بازخوردها",
                "db_table": "api_feedback_entry",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="FeedbackTagLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("personal", "بعد فردی"),
                            ("career", "مسیر رشد و انتظارات"),
                            ("performance", "مدیریت عملکرد"),
                            ("communication", "تعامل و مشتری\u200cمحوری"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feedback"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.valuetag"
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ بازخورد",
                "verbose_name_plural": "تگ\u200cهای بازخورد",
                "unique_together": {("feedback", "tag", "section")},
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="tags",
            field=models.ManyToManyField(
                related_name="feedback_tags",
                through="api.FeedbackTagLink",
                to="api.valuetag",
            ),
        ),
        migrations.CreateModel(
            name="FeedbackRequestUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answered", models.BooleanField(default=False)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requestees",
                        to="api.feedbackrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک درخواست بازخورد",
                "verbose_name_plural": "لینک\u200cهای درخواست بازخورد",
                "unique_together": {("request", "user")},
            },
        ),
    ]
