# Generated by Django 5.0.1 on 2025-07-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_ladder_payband_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="level",
        ),
    ]
