# Generated by Django 5.0.1 on 2025-07-28 15:01

import api.models.note
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_user_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committee",
            name="committee_type",
        ),
        migrations.AddField(
            model_name="note",
            name="proposal_type",
            field=models.CharField(
                choices=[
                    ("PROMOTION", "ارتقا"),
                    ("NOTICE", "نوتیس"),
                    ("MAPPING", "مپینگ اولیه"),
                    ("EVALUATION", "ارزیابی"),
                ],
                default=api.models.note.ProposalType.default,
                max_length=16,
                verbose_name="نوع پروپوزال",
            ),
        ),
    ]
