# Generated by Django 5.0.1 on 2025-07-15 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_feedbackform_alter_note_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "ارگانیزیشن",
                "verbose_name_plural": "ارگانیزیشن\u200cها",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="cfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_cfo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سی\u200cاف\u200cاو",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hr_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_hr_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر اچ\u200cآر",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sales_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_sales_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر فروش",
            ),
        ),
    ]
