# Generated by Django 5.0.1 on 2025-07-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_remove_committee_committee_type_note_proposal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="aspect_changes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="تغییرات ابعاد لدر"
            ),
        ),
        migrations.AddField(
            model_name="summary",
            name="ladder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.ladder",
                verbose_name="لدر",
            ),
        ),
    ]
