# Generated by Django 5.0.1 on 2025-07-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_alter_organization_options_organization_cfo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "سازمان", "verbose_name_plural": "سازمان\u200cها"},
        ),
    ]
