# Generated by Django 5.0.1 on 2025-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_summary_aspect_changes_summary_ladder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SENIORITY_CHANGE", "تغییر سطح لدر"),
                    ("PAY_CHANGE", "تغییر بسته\u200c حقوقی"),
                    ("BONUS_PAYOUT", "پرداخت پاداش"),
                    ("EVALUATION", "خروجی ارزیابی کمیته"),
                    ("MAPPING", "بازنشانی روی لدر"),
                    ("TITLE_CHANGE", "تغییر عنوان شغلی"),
                    ("STOCK_GRANT", "اعطای سهام"),
                    ("NOTICE", "نوتیس"),
                    ("LADDER_CHANGED", "تغییر لدر"),
                ],
                default="EVALUATION",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="summary_text",
            field=models.CharField(max_length=512),
        ),
    ]
