# Generated by Django 5.0.1 on 2025-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_summary_aspect_changes_summary_ladder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineevent",
            name="summary_text",
            field=models.CharField(max_length=512),
        ),
    ]
