# Generated by Django 5.0.1 on 2025-08-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_alter_timelineevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="senioritysnapshot",
            name="stages_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
