# Generated by Django 5.0.1 on 2025-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_senioritysnapshot_stages_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladderlevel",
            name="stage",
            field=models.CharField(
                choices=[
                    ("ابتدای سطح", "ابتدای سطح"),
                    ("میانه سطح", "میانه سطح"),
                    ("انتهای سطح", "انتهای سطح"),
                ],
                default="ابتدای سطح",
                max_length=16,
            ),
        ),
    ]
