# Generated by Django 5.0.1 on 2025-08-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_alter_ladderlevel_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="ladder_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ابتدای سطح", "ابتدای سطح"),
                    ("میانه\u200c سطح", "میانه سطح"),
                    ("انتهای سطح", "انتهای سطح"),
                ],
                default="ابتدای سطح",
                max_length=16,
                null=True,
                verbose_name="مرحله لدر",
            ),
        ),
        migrations.AlterField(
            model_name="ladderlevel",
            name="stage",
            field=models.CharField(
                choices=[
                    ("ابتدای سطح", "ابتدای سطح"),
                    ("میانه\u200c سطح", "میانه سطح"),
                    ("انتهای سطح", "انتهای سطح"),
                ],
                default="ابتدای سطح",
                max_length=16,
            ),
        ),
    ]
