# Generated by Django 5.0.1 on 2025-08-12 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_alter_ladderlevel_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgAssignmentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("effective_date", models.DateField()),
            ],
            options={
                "verbose_name": "اسنپ\u200cشات انتساب سازمانی",
                "verbose_name_plural": "اسنپ\u200cشات\u200cهای انتساب سازمانی",
                "ordering": ("-effective_date",),
            },
        ),
        migrations.AddField(
            model_name="compensationsnapshot",
            name="salary_change",
            field=models.FloatField(
                default=0.0, help_text="Delta steps applied; supports 0.5 increments"
            ),
        ),
        migrations.AlterField(
            model_name="ladderlevel",
            name="stage",
            field=models.CharField(
                choices=[
                    ("ابتدای سطح", "ابتدای سطح"),
                    ("میانه\u200c سطح", "میانه سطح"),
                    ("انتهای سطح", "انتهای سطح"),
                ],
                default="ابتدای سطح",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payband",
            name="number",
            field=models.FloatField(unique=True, verbose_name="شماره پله"),
        ),
        migrations.AddIndex(
            model_name="compensationsnapshot",
            index=models.Index(
                fields=["user", "effective_date"], name="api_compens_user_id_9a0626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compensationsnapshot",
            index=models.Index(
                fields=["pay_band", "effective_date"],
                name="api_compens_pay_ban_2e29cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="senioritysnapshot",
            index=models.Index(
                fields=["user", "effective_date"], name="api_seniori_user_id_e18a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="senioritysnapshot",
            index=models.Index(
                fields=["ladder", "effective_date"],
                name="api_seniori_ladder__cd3d5d_idx",
            ),
        ),
        migrations.AddField(
            model_name="orgassignmentsnapshot",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.chapter",
            ),
        ),
        migrations.AddField(
            model_name="orgassignmentsnapshot",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
            ),
        ),
        migrations.AddField(
            model_name="orgassignmentsnapshot",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_leader_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orgassignmentsnapshot",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.team",
            ),
        ),
        migrations.AddField(
            model_name="orgassignmentsnapshot",
            name="tribe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.tribe",
            ),
        ),
        migrations.AddField(
            model_name="orgassignmentsnapshot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="orgassignmentsnapshot",
            index=models.Index(
                fields=["user", "effective_date"], name="api_orgassi_user_id_99b0a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgassignmentsnapshot",
            index=models.Index(
                fields=["leader", "effective_date"],
                name="api_orgassi_leader__f84d35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orgassignmentsnapshot",
            index=models.Index(
                fields=["team", "effective_date"], name="api_orgassi_team_id_583249_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgassignmentsnapshot",
            index=models.Index(
                fields=["tribe", "effective_date"],
                name="api_orgassi_tribe_i_8971f9_idx",
            ),
        ),
    ]
