# Generated by Django 5.0.1 on 2025-08-12 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_orgassignmentsnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAccessOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ALL", "All users"),
                            ("TECH", "Technical users"),
                            ("PRODUCT", "Product users"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Data Access Override",
                "verbose_name_plural": "Data Access Overrides",
            },
        ),
        migrations.AddIndex(
            model_name="summary",
            index=models.Index(
                fields=["committee_date"], name="api_summary_committ_0f485b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summary",
            index=models.Index(
                fields=["note", "committee_date"], name="api_summary_note_id_88320b_idx"
            ),
        ),
        migrations.AddField(
            model_name="dataaccessoverride",
            name="granted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="granted_access_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataaccessoverride",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_access_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dataaccessoverride",
            index=models.Index(
                fields=["user", "is_active"], name="api_dataacc_user_id_fdad20_idx"
            ),
        ),
    ]
