# Generated by Django 5.0.1 on 2025-08-17 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_dataaccessoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECH", "فنی"),
                    ("PRODUCT", "محصول"),
                    ("NON_TECH", "غیر فنی"),
                    ("OTHER", "دیگر"),
                ],
                max_length=16,
                null=True,
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AddField(
            model_name="tribe",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECH", "فنی"),
                    ("PRODUCT", "محصول"),
                    ("NON_TECH", "غیر فنی"),
                    ("OTHER", "دیگر"),
                ],
                max_length=16,
                null=True,
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="cfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_cfo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر مالی",
            ),
        ),
    ]
