# Generated by Django 5.0.1 on 2025-08-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_team_category_tribe_category_alter_organization_cfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("TECH", "فنی"), ("NON_TECH", "غیر فنی")],
                max_length=16,
                null=True,
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="tribe",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("TECH", "فنی"), ("NON_TECH", "غیر فنی")],
                max_length=16,
                null=True,
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AddIndex(
            model_name="compensationsnapshot",
            index=models.Index(
                condition=models.Q(("source_event__isnull", False)),
                fields=["user", "effective_date", "source_event"],
                name="unique_comp_snapshot_per_event",
            ),
        ),
        migrations.AddIndex(
            model_name="senioritysnapshot",
            index=models.Index(
                condition=models.Q(("source_event__isnull", False)),
                fields=["user", "ladder", "effective_date", "source_event"],
                name="unique_sen_snapshot_per_event",
            ),
        ),
    ]
