# Generated by Django 5.0.1 on 2025-08-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_alter_team_category_alter_tribe_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="maintainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_maintainer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نگهدارنده",
            ),
        ),
    ]
