# Generated by Django 5.0.1 on 2025-10-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_organization_maintainer"),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_import',
            field=models.BooleanField(default=False, verbose_name="وارد شده از ایمپورت"),
        ),
        migrations.AddField(
            model_name='note',
            name='_skip_access_grants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='is_import',
            field=models.BooleanField(default=False, verbose_name="وارد شده از ایمپورت"),
        ),
    ]
