# Generated by Django 5.0.1 on 2025-10-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_auto_20251014_1930"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackrequest",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedbackrequest",
            name="public_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="_skip_access_grants",
            field=models.BooleanField(
                default=False, verbose_name="رد دسترسی\u200cهای خودکار"
            ),
        ),
    ]
