# Generated by Django 5.0.1 on 2025-11-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_feedbackrequest_is_public_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackrequest",
            name="public_token",
        ),
    ]
