# Generated by Django 5.0.1 on 2025-11-03 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_remove_feedbackrequest_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="senioritysnapshot",
            name="seniority_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JUNIOR", "Junior"),
                    ("MID", "Mid"),
                    ("SENIOR", "Senior"),
                    ("PRINCIPAL", "Principal"),
                ],
                help_text="Seniority classification (Junior/Mid/Senior/Principal) for data analytics",
                max_length=20,
                null=True,
                verbose_name="Seniority Level",
            ),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ ساخت"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this API key (e.g., 'Metabase Integration')",
                        max_length=256,
                        verbose_name="Key Name",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 12 characters of the key (for identification)",
                        max_length=12,
                        verbose_name="Key Prefix",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hashed version of the API key",
                        max_length=128,
                        verbose_name="Key Hash",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful authentication with this key",
                        null=True,
                        verbose_name="Last Used",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this API key is active and can be used",
                        verbose_name="Active",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User account associated with this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ("-date_created",),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="api_apikey_user_id_90f679_idx",
                    )
                ],
            },
        ),
    ]
