# Generated by Django 5.0.1 on 2025-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_senioritysnapshot_seniority_level_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="seniority_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JUNIOR", "Junior"),
                    ("MID", "Mid"),
                    ("SENIOR", "Senior"),
                    ("PRINCIPAL", "Principal"),
                ],
                help_text="Optional seniority classification (Junior/Mid/Senior/Principal)",
                max_length=20,
                null=True,
                verbose_name="سطح سنیوریتی",
            ),
        ),
    ]
