# Generated by Django 5.0.1 on 2025-11-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_emailtemplate_emaillog_emailtrigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtrigger",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_form_assigned", "New Form Assigned"),
                    ("unchecked_form_reminder", "Unchecked Form Reminder"),
                    ("user_mentioned", "User Mentioned in Note"),
                ],
                help_text="Event that triggers the email",
                max_length=100,
            ),
        ),
    ]
