# Generated by Django 5.0.1 on 2025-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_alter_emailtrigger_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtrigger",
            name="conditions",
        ),
        migrations.AlterField(
            model_name="emailtrigger",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_form_assigned", "New Form Assigned"),
                    ("unchecked_form_reminder", "Unchecked Form Reminder"),
                    ("user_mentioned", "User Mentioned in Note"),
                ],
                help_text="Event that triggers the email",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailtrigger",
            name="placeholders",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Maps template placeholders to user attributes (e.g., {"user_name": "name", "user_role": "role"})',
            ),
        ),
    ]
